In [3]:
from __future__ import print_function
import torch

In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[4.5581e+30, 1.1725e-19, 5.0746e+31],
        [7.5338e+28, 2.8884e+12, 7.5338e+28],
        [1.5769e-19, 1.9432e-19, 1.8888e+31],
        [2.9597e+21, 2.8181e+20, 1.8061e+28],
        [2.8376e+20, 1.8180e+31, 2.0283e-19]])


In [5]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1715, 0.4626, 0.6902],
        [0.5620, 0.8266, 0.8866],
        [0.2846, 0.5883, 0.6102],
        [0.0704, 0.8294, 0.0560],
        [0.2023, 0.7246, 0.4332]])


In [6]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [10]:
x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[0.0469, 0.9629, 0.3957],
        [0.9212, 0.7537, 0.3306],
        [0.0216, 0.3297, 0.1184],
        [0.4033, 0.8318, 0.0614],
        [0.2631, 0.0715, 0.4692]])


In [11]:
print(x.size())

torch.Size([5, 3])


In [12]:
y = torch.rand(5, 3)
print(x + y)

tensor([[0.9384, 1.4413, 0.9140],
        [1.7698, 1.0302, 0.8415],
        [0.5311, 1.1955, 0.3255],
        [0.9320, 1.1802, 0.1086],
        [1.1684, 0.6606, 1.2962]])


In [13]:
print(torch.add(x, y))

tensor([[0.9384, 1.4413, 0.9140],
        [1.7698, 1.0302, 0.8415],
        [0.5311, 1.1955, 0.3255],
        [0.9320, 1.1802, 0.1086],
        [1.1684, 0.6606, 1.2962]])


In [14]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.9384, 1.4413, 0.9140],
        [1.7698, 1.0302, 0.8415],
        [0.5311, 1.1955, 0.3255],
        [0.9320, 1.1802, 0.1086],
        [1.1684, 0.6606, 1.2962]])


In [15]:
y.add_(x)

tensor([[0.9384, 1.4413, 0.9140],
        [1.7698, 1.0302, 0.8415],
        [0.5311, 1.1955, 0.3255],
        [0.9320, 1.1802, 0.1086],
        [1.1684, 0.6606, 1.2962]])

In [16]:
print(x[:, 1])

tensor([0.9629, 0.7537, 0.3297, 0.8318, 0.0715])


In [17]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [18]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.0429])
1.0429261922836304


In [19]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [20]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [21]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [22]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)

np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [23]:
torch.cuda.is_available()

True

In [24]:
device = torch.device("cuda")
y = torch.ones_like(x, device=device)
x = x.to(device)
z = x + y
print(z)
print(z.to("cpu", torch.double))

tensor([2.0429], device='cuda:0')
tensor([2.0429], dtype=torch.float64)
