In [1]:
import tensorflow as tf

In [4]:
tf.constant("こんにちは、世界")

<tf.Tensor: id=2, shape=(), dtype=string, numpy=b'\xe3\x81\x93\xe3\x82\x93\xe3\x81\xab\xe3\x81\xa1\xe3\x81\xaf\xe3\x80\x81\xe4\xb8\x96\xe7\x95\x8c'>

In [5]:
tf.constant(["you're", "welcome!"]).shape

TensorShape([2])

In [7]:
text_utf8 = tf.constant("言語処理")
text_utf8

<tf.Tensor: id=4, shape=(), dtype=string, numpy=b'\xe8\xa8\x80\xe8\xaa\x9e\xe5\x87\xa6\xe7\x90\x86'>

In [9]:
text_utf16be = tf.constant("言語処理".encode("UTF-16-BE"))
text_utf16be

<tf.Tensor: id=6, shape=(), dtype=string, numpy=b'\x8a\x00\x8a\x9eQ\xe6t\x06'>

In [11]:
text_chars = tf.constant([ord(char) for char in "言語処理"])
text_chars

<tf.Tensor: id=7, shape=(4,), dtype=int32, numpy=array([35328, 35486, 20966, 29702], dtype=int32)>

In [12]:
tf.strings.unicode_decode(text_utf8, input_encoding='UTF-8')

<tf.Tensor: id=11, shape=(4,), dtype=int32, numpy=array([35328, 35486, 20966, 29702], dtype=int32)>

In [13]:
tf.strings.unicode_encode(text_chars, output_encoding='UTF-8')

<tf.Tensor: id=21, shape=(), dtype=string, numpy=b'\xe8\xa8\x80\xe8\xaa\x9e\xe5\x87\xa6\xe7\x90\x86'>

In [14]:
tf.strings.unicode_transcode(text_utf8,
                             input_encoding='UTF-8',
                             output_encoding='UTF-16-BE')

<tf.Tensor: id=22, shape=(), dtype=string, numpy=b'\x8a\x00\x8a\x9eQ\xe6t\x06'>

In [15]:
batch_utf8 = [s.encode('UTF-8') for s in 
              ["hello", "こんにちは", "what is the weather tommorow", "おやすみ"]]

batch_chars_ragged = tf.strings.unicode_decode(batch_utf8,
                                              input_encoding='UTF-8')

for sentence_chars in batch_chars_ragged.to_list():
    print(sentence_chars)

[104, 101, 108, 108, 111]
[12371, 12435, 12395, 12385, 12399]
[119, 104, 97, 116, 32, 105, 115, 32, 116, 104, 101, 32, 119, 101, 97, 116, 104, 101, 114, 32, 116, 111, 109, 109, 111, 114, 111, 119]
[12362, 12420, 12377, 12415]


In [16]:
batch_chars_padded = batch_chars_ragged.to_tensor(default_value=-1)
print(batch_chars_padded.numpy())

[[  104   101   108   108   111    -1    -1    -1    -1    -1    -1    -1
     -1    -1    -1    -1    -1    -1    -1    -1    -1    -1    -1    -1
     -1    -1    -1    -1]
 [12371 12435 12395 12385 12399    -1    -1    -1    -1    -1    -1    -1
     -1    -1    -1    -1    -1    -1    -1    -1    -1    -1    -1    -1
     -1    -1    -1    -1]
 [  119   104    97   116    32   105   115    32   116   104   101    32
    119   101    97   116   104   101   114    32   116   111   109   109
    111   114   111   119]
 [12362 12420 12377 12415    -1    -1    -1    -1    -1    -1    -1    -1
     -1    -1    -1    -1    -1    -1    -1    -1    -1    -1    -1    -1
     -1    -1    -1    -1]]


In [18]:
batch_chars_sparse = batch_chars_ragged.to_sparse()
print(batch_chars_sparse)

SparseTensor(indices=tf.Tensor(
[[ 0  0]
 [ 0  1]
 [ 0  2]
 [ 0  3]
 [ 0  4]
 [ 1  0]
 [ 1  1]
 [ 1  2]
 [ 1  3]
 [ 1  4]
 [ 2  0]
 [ 2  1]
 [ 2  2]
 [ 2  3]
 [ 2  4]
 [ 2  5]
 [ 2  6]
 [ 2  7]
 [ 2  8]
 [ 2  9]
 [ 2 10]
 [ 2 11]
 [ 2 12]
 [ 2 13]
 [ 2 14]
 [ 2 15]
 [ 2 16]
 [ 2 17]
 [ 2 18]
 [ 2 19]
 [ 2 20]
 [ 2 21]
 [ 2 22]
 [ 2 23]
 [ 2 24]
 [ 2 25]
 [ 2 26]
 [ 2 27]
 [ 3  0]
 [ 3  1]
 [ 3  2]
 [ 3  3]], shape=(42, 2), dtype=int64), values=tf.Tensor(
[  104   101   108   108   111 12371 12435 12395 12385 12399   119   104
    97   116    32   105   115    32   116   104   101    32   119   101
    97   116   104   101   114    32   116   111   109   109   111   114
   111   119 12362 12420 12377 12415], shape=(42,), dtype=int32), dense_shape=tf.Tensor([ 4 28], shape=(2,), dtype=int64))


In [19]:
tf.strings.unicode_encode([[99, 97, 116], [100, 111, 103],
                           [99, 111, 119]], output_encoding='UTF-8')

<tf.Tensor: id=125, shape=(3,), dtype=string, numpy=array([b'cat', b'dog', b'cow'], dtype=object)>

In [21]:
tf.strings.unicode_encode(batch_chars_padded, output_encoding='UTF-8')

<tf.Tensor: id=152, shape=(4,), dtype=string, numpy=
array([b'hello\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd',
       b'\xe3\x81\x93\xe3\x82\x93\xe3\x81\xab\xe3\x81\xa1\xe3\x81\xaf\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd',
       b'what is the weather tommorow',
       b'\xe3\x81\x8a\xe3\x82\x84\xe3\x81\x99\xe3\x81\xbf\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\xbf\xbd\xef\

In [22]:
tf.strings.unicode_encode(batch_chars_ragged, output_encoding='UTF-8')

<tf.Tensor: id=153, shape=(4,), dtype=string, numpy=
array([b'hello',
       b'\xe3\x81\x93\xe3\x82\x93\xe3\x81\xab\xe3\x81\xa1\xe3\x81\xaf',
       b'what is the weather tommorow',
       b'\xe3\x81\x8a\xe3\x82\x84\xe3\x81\x99\xe3\x81\xbf'], dtype=object)>

In [23]:
tf.strings.unicode_encode(
    tf.RaggedTensor.from_sparse(batch_chars_sparse),
    output_encoding='UTF-8')

<tf.Tensor: id=232, shape=(4,), dtype=string, numpy=
array([b'hello',
       b'\xe3\x81\x93\xe3\x82\x93\xe3\x81\xab\xe3\x81\xa1\xe3\x81\xaf',
       b'what is the weather tommorow',
       b'\xe3\x81\x8a\xe3\x82\x84\xe3\x81\x99\xe3\x81\xbf'], dtype=object)>

In [24]:
tf.strings.unicode_encode(
    tf.RaggedTensor.from_tensor(batch_chars_padded, padding=-1),
    output_encoding='UTF-8')

<tf.Tensor: id=305, shape=(4,), dtype=string, numpy=
array([b'hello',
       b'\xe3\x81\x93\xe3\x82\x93\xe3\x81\xab\xe3\x81\xa1\xe3\x81\xaf',
       b'what is the weather tommorow',
       b'\xe3\x81\x8a\xe3\x82\x84\xe3\x81\x99\xe3\x81\xbf'], dtype=object)>

In [26]:
thanks = "thank you, ありがとう".encode('UTF-8')
num_bytes = tf.strings.length(thanks).numpy()
num_chars = tf.strings.length(thanks, unit='UTF8_CHAR').numpy()
print("{} bytes : {} UTF-8 characters".format(num_bytes, num_chars))

26 bytes : 16 UTF-8 characters


In [29]:
tf.strings.substr(thanks, pos=13, len=1).numpy()

b'\x82'

In [32]:
print(tf.strings.substr(thanks, pos=12, len=1, unit='UTF8_CHAR').numpy())

b'\xe3\x82\x8a'


In [33]:
tf.strings.unicode_split(thanks, 'UTF-8').numpy()


array([b't', b'h', b'a', b'n', b'k', b' ', b'y', b'o', b'u', b',', b' ',
       b'\xe3\x81\x82', b'\xe3\x82\x8a', b'\xe3\x81\x8c', b'\xe3\x81\xa8',
       b'\xe3\x81\x86'], dtype=object)

In [35]:
codepoints, offsets = tf.strings.unicode_decode_with_offsets("🎈🎉🎊", 'UTF-8')
for (codepoint, offset) in zip(codepoints.numpy(), offsets.numpy()):
    print("At byte offset {}: codepoint {}".format(offset, codepoint))

At byte offset 0: codepoint 127880
At byte offset 4: codepoint 127881
At byte offset 8: codepoint 127882


In [37]:
unscript = tf.strings.unicode_script([33464, 1041])
print(unscript.numpy())

[17  8]


In [38]:
print(tf.strings.unicode_script(batch_chars_ragged))

<tf.RaggedTensor [[25, 25, 25, 25, 25], [20, 20, 20, 20, 20], [25, 25, 25, 25, 0, 25, 25, 0, 25, 25, 25, 0, 25, 25, 25, 25, 25, 25, 25, 0, 25, 25, 25, 25, 25, 25, 25, 25], [20, 20, 20, 20]]>


In [44]:
sentence_texts = ["Hello, world.", "こんにちは"]
sentence_char_codepoint = tf.strings.unicode_decode(sentence_texts, 'UTF-8')
print(sentence_char_codepoint)

sentence_char_scrpit = tf.strings.unicode_script(sentence_char_codepoint)
print(sentence_char_scrpit)

<tf.RaggedTensor [[72, 101, 108, 108, 111, 44, 32, 119, 111, 114, 108, 100, 46], [12371, 12435, 12395, 12385, 12399]]>
<tf.RaggedTensor [[25, 25, 25, 25, 25, 0, 0, 25, 25, 25, 25, 25, 0], [20, 20, 20, 20, 20]]>


In [47]:
sentence_char_starts_word = tf.concat(
    [tf.fill([sentence_char_scrpit.nrows(), 1], True),
    tf.not_equal(sentence_char_scrpit[:, 1:], sentence_char_scrpit[:, :-1])],
    axis=1)

In [48]:
word_starts = tf.squeeze(tf.where(sentence_char_starts_word.values))
print(word_starts)

tf.Tensor([ 0  5  7 12 13], shape=(5,), dtype=int64)


In [51]:
tf.fill([sentence_char_scrpit.nrows(), 1], True)
tf.not_equal(sentence_char_scrpit[:, 1:], sentence_char_scrpit[:, :-1])

<tf.RaggedTensor [[False, False, False, False, True, False, True, False, False, False, False, True], [False, False, False, False]]>

In [52]:
word_char_codepoint = tf.RaggedTensor.from_row_starts(
    values=sentence_char_codepoint.values,
    row_starts=word_starts)
print(word_char_codepoint)

<tf.RaggedTensor [[72, 101, 108, 108, 111], [44, 32], [119, 111, 114, 108, 100], [46], [12371, 12435, 12395, 12385, 12399]]>


In [53]:
word_char_codepoint = tf.RaggedTensor.from_row_starts(
    values=sentence_char_codepoint.values,
    row_starts=word_starts)
print(word_char_codepoint)

<tf.RaggedTensor [[72, 101, 108, 108, 111], [44, 32], [119, 111, 114, 108, 100], [46], [12371, 12435, 12395, 12385, 12399]]>
